version: "3.8"

services:
  db:
    container_name: test-db
    image: postgres:15-alpine
    # log all slow queries to console
    command: [ "postgres", "-c", "log_min_duration_statement=1000" ]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      # initial data is handled by migrations
      # uncomment this if you want to use a db init script
      - ./.docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  backend:
    container_name: backend
    build: .
    ports:
      - "5001:5001"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
volumes:
  pgdata: